cores: [0]
memory:
  packet_pool: 2048
  shared_memory: 1024
log_level: debug
nics:
  - dev: 'enp0s8'
    mac: '08:00:27:48:ea:67'
    ipv4: '192.168.1.11'
    ipv6: auto
    rx_queue: 1024
    tx_queue: 1024
    promisc: false
    rx_offloads:
      - vlan_strip
      - vlan_filter
      - ipv4_cksum
    tx_offloads:
      - vlan_insert
      - ipv4_cksum

