#ifndef __PV_OFFLOAD_H__
#define __PV_OFFLOAD_H__

enum pv_pkt_rx_offload_type {
    PV_PKT_RX_VLAN = 1 << 0,
    PV_PKT_RX_VLAN_STRIPPED = 1 << 1,

    PV_PKT_RX_IP_CKSUM_UNKNOWN = 0,
    PV_PKT_RX_IP_CKSUM_GOOD = 1 << 2,
    PV_PKT_RX_IP_CKSUM_BAD = 1 << 3,
    PV_PKT_RX_IP_CKSUM_MASK = PV_PKT_RX_IP_CKSUM_GOOD | PV_PKT_RX_IP_CKSUM_BAD,
    PV_PKT_RX_IP_CKSUM_NONE = PV_PKT_RX_IP_CKSUM_MASK,
};

#endif
