name: Lint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Cargo fmt
        uses: actions-rust-lang/rustfmt@v1
      - name: Cargo clippy
        uses: giraffate/clippy-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --examples
      - name: shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: >-
            bpftool
            xdp-tools
      - name: Final newline
        uses: Logerfo/newline-action@0.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/newline.yml
      - name: Check trailing whitespaces
        uses: ocular-d/trailing-spaces@main
