name: Lint

on:
  - push
  - pull_request

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@1
        with:
          python-version: "3.9"
      - name: Flake8
        uses: py-actions/flake8@v1
